json.id product.id
json.name product.name
json.price product.price
json.img_url product.img_url
json.description product.description
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.friendly_created_at product.friendly_created_at
json.created_at product.created_at
json.updated_at product.updated_at
json.inventory product.inventory
